import Head from 'next/head'
import FormContainer from '../components/Registration/Form/FormContainer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DATASUB_front</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.datasub.com/">DATASUB</a> payments
        </h1>

        <FormContainer/>
      </main>

    </div>
  )
}
